🚀 Full CI/CD Pipeline for GitDigital Automation Engine
Place this in:

`
.github/workflows/ci-cd.yml
`

`yaml
name: GitDigital Automation Engine CI/CD

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

jobs:
  ci:
    name: Build & Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: TypeScript compile check
        run: npm run build --if-present

      - name: Run unit tests
        run: npm run test --if-present

      - name: Start automation engine (background)
        run: |
          nohup npm run dev > server.log 2>&1 &
          sleep 5

      - name: Run integration tests
        run: npm run test:integration --if-present

      - name: Run E2E tests
        run: npm run test:e2e --if-present

      - name: Upload server logs on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: server-logs
          path: server.log

  docker-build:
    name: Build Docker Image
    runs-on: ubuntu-latest
    needs: ci

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        run: |
          docker build -t ghcr.io/${{ github.repository }}/automation-engine:latest .

      - name: Push Docker image
        run: |
          docker push ghcr.io/${{ github.repository }}/automation-engine:latest

  deploy:
    name: Deploy to Production
    runs-on: ubuntu-latest
    needs: docker-build
    if: github.ref == 'refs/heads/main'

    steps:
      - name: SSH into server and deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.PRODSERVERHOST }}
          username: ${{ secrets.PRODSERVERUSER }}
          key: ${{ secrets.PRODSERVERSSH_KEY }}
          script: |
            docker pull ghcr.io/${{ github.repository }}/automation-engine:latest
            docker stop automation-engine || true
            docker rm automation-engine || true
            docker run -d \
              --name automation-engine \
              -p 3000:3000 \
              ghcr.io/${{ github.repository }}/automation-engine:latest
`

---

🧠 What This Pipeline Gives You

1. CI (Quality Gate)
- TypeScript build  
- Unit tests  
- Integration tests  
- E2E tests  
- Server logs on failure  

2. CD (Deployment)
- Build Docker image  
- Push to GitHub Container Registry  
- SSH into your production server  
- Pull latest image  
- Restart container cleanly  

3. Safe, deterministic, contributor‑friendly
- PRs must pass CI  
- Only main deploys  
- No manual steps  
- No hidden state  

---

🔐 Required Secrets

Add these in GitHub → Settings → Secrets → Actions:

| Secret | Purpose |
|--------|---------|
| PRODSERVERHOST | IP or domain of your server |
| PRODSERVERUSER | SSH username |
| PRODSERVERSSH_KEY | Private key for deployment |

---

